### ISSUE TITLE
Feature 1: User can create a marker to enter a rec

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#1]
## ⚙️ Feature

Users can create a marker to enter a recommendation

## 📐 Functionality

click on the map and enter an entry

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 42 33 AM](https://user-images.githubusercontent.com/91447324/163858154-09599ef4-f871-4baa-b94b-452fb3a55a75.png)

## ✅ Task List

- [x] make index html
- [x] import custom map from google maps api
- [x] do styling
- [x] create "make a rec" button
- [x] create modal when button is clicked 
- [x] make event listener for click on map through js
- [x] save lat lang when clicked and **[move to second feature] -->** center screen to that point 
- [x] make popup and modal to get friend 
- [x] make image placeholder a drag and drop or click to add file
- [x] when form is submitted a new popup opens to submit form for a rec with image and friend name saved
- [x] tag is created when typed in text input and + button is clicked **[move to second feature]**
- [x] when form is submitted the friend image is seen on map as marker
