### ISSUE TITLE
Design Update: Fix UI for mobile

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#19]
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Make layout look better for mobile

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]  change mobile view to have rec image take up width 
- [ ] have tags take width
- [ ] notes take width
- [ ] put options button still on botom right
- [ ] change eventListener for options button
- Tablet View
  - [ ] make sliding component at ____ px for media query to keep windows format
