### ISSUE TITLE
Feature 2: User can view list of recs

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#2]
## ⚙️ Feature

User can view list of recs when a marker is created

## 📐 Functionality

recs are listed on the side of the screen and can scroll for multiple entries

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 54 40 AM](https://user-images.githubusercontent.com/91447324/163860065-7210ea23-7aa8-475c-b54f-b4df9f7d564a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make sample html to put in entries list as an entry
- [x] do styling for web and mobile
- [x] make function for dom tree for entry to put in entries list
- [x] test out multiple entries for web
- [x] test out multiple entries for mobile
- [x] make tags for logging entry
- [x] include tags in dom tree for an entry
- [x] saved to local storage to recall
- [x] fix up css and errors
