### ISSUE TITLE
Feature 3: User can edit rec entries 

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#3]
## ⚙️ Feature

User can edit rec entries

## 📐 Functionality

can click on ... button and click on edit button

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 56 00 AM](https://user-images.githubusercontent.com/91447324/163860267-bcc27324-4a45-4340-a19d-005ce3e0b665.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make html skeleton of entry with ... button 
- [x] make styling to show circle shadow on hover
- [x] make event listener to click and stay shadowed
- [x] show element with edit button on click
- [x] edit button shadow on hover
- [x] pull up entries form on edit with data values
- [x] make sure data is edited when edit
- [x] edit marker img if img is changed
- [x] make sure dom updates in correct order
- [x] fix styling, errors
- [x] delete comments
- [x] test
