### ISSUE TITLE
Feature 4: User can delete a rec

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#4]
## ⚙️ Feature

User can delete a rec entry

## 📐 Functionality

delete an entry if no longer wanted

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 56 00 AM](https://user-images.githubusercontent.com/91447324/163860388-4cbee065-de42-4d51-9f58-373951bae3c3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make delete button on dom tree
- [x] include add event listener to delete button and console log
- [x] make modal for delete confirmation
- [x] make event listener for cancel delete or confirm
- [x] console log ^^
- [x] if delete remove entry from dom tree and data
- [x] remove marker to update when entry is deleted
- [x] fix any errors and css
- [x] test more
