### ISSUE TITLE
Feature 5: User can focus on an entry

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#5]
## ⚙️ Feature

user can focus on an entry on the map and on the entry list

## 📐 Functionality

can click on map marker to focus on entry and vise versa

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 58 33 AM](https://user-images.githubusercontent.com/91447324/163860578-a6dc7e84-efc4-46b3-9e09-3d21c13f3f1c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make event listener for a li element
- [x] console log li element data-entry-id
- [x] make event listener for each marker
- [x] console log the marker details 
- [x] make styling for click highlight for entry 
- [x] make styling for marker highlight in map
- [x] make for loop to match click on marker / click on entry 
- [x] enabel styling when clicked
- [x] center marker when "focused"
- [x] review styling
- [x] check errors
- [x] test
