### ISSUE TITLE
Feature 6 : User can save friends

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/marker-Recs#6]
## ⚙️ Feature

user can save friends

## 📐 Functionality

can save friends to pull up later if they have another recommendation

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 59 55 AM](https://user-images.githubusercontent.com/91447324/163860769-e1aba238-f339-407c-b855-4134307c1d07.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] change add friend entry to adding friend 
- [x] make a form modal with select optiojns
- [x] create button for adding a friend 
- [x] link add friend button in select friend modal to go to add friend modal
- [x] edit select option values to have entry friend id 
- [x] when select has event listener to change - see the value of that entry id and get that friendID's photo
- [x] when a new friend gets added - add to select options
- [x] ^^ go back to select friend form
- [x] run tests
- [x] fix errors
- [x] run more tests
